#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure_ac
# autospec version: v21
# autospec commit: be3faa5
#
# Source0 file verified with key 0xFC57E3CCACD99A78 (mjw@gnu.org)
#
%define keepstatic 1
Name     : bzip2
Version  : 1.0.8
Release  : 59
URL      : https://sourceware.org/pub/bzip2/bzip2-1.0.8.tar.gz
Source0  : https://sourceware.org/pub/bzip2/bzip2-1.0.8.tar.gz
Source1  : https://sourceware.org/pub/bzip2/bzip2-1.0.8.tar.gz.sig
Source2  : FC57E3CCACD99A78.pkey
Summary  : Data compressor
Group    : Development/Tools
License  : bzip2-1.0.6
Requires: bzip2-bin = %{version}-%{release}
Requires: bzip2-lib = %{version}-%{release}
Requires: bzip2-license = %{version}-%{release}
Requires: bzip2-man = %{version}-%{release}
BuildRequires : file
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : gnupg
BuildRequires : patchelf
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Autotoolize-bzip2.patch
Patch2: 0002-Improve-file-access.patch

%description
This version is fully compatible with the previous public releases.
------------------------------------------------------------------
This file is part of bzip2/libbzip2, a program and library for
lossless, block-sorting data compression.

%package bin
Summary: bin components for the bzip2 package.
Group: Binaries
Requires: bzip2-license = %{version}-%{release}

%description bin
bin components for the bzip2 package.


%package dev
Summary: dev components for the bzip2 package.
Group: Development
Requires: bzip2-lib = %{version}-%{release}
Requires: bzip2-bin = %{version}-%{release}
Provides: bzip2-devel = %{version}-%{release}
Requires: bzip2 = %{version}-%{release}

%description dev
dev components for the bzip2 package.


%package dev32
Summary: dev32 components for the bzip2 package.
Group: Default
Requires: bzip2-lib32 = %{version}-%{release}
Requires: bzip2-bin = %{version}-%{release}
Requires: bzip2-dev = %{version}-%{release}

%description dev32
dev32 components for the bzip2 package.


%package lib
Summary: lib components for the bzip2 package.
Group: Libraries
Requires: bzip2-license = %{version}-%{release}

%description lib
lib components for the bzip2 package.


%package lib32
Summary: lib32 components for the bzip2 package.
Group: Default
Requires: bzip2-license = %{version}-%{release}

%description lib32
lib32 components for the bzip2 package.


%package license
Summary: license components for the bzip2 package.
Group: Default

%description license
license components for the bzip2 package.


%package man
Summary: man components for the bzip2 package.
Group: Default

%description man
man components for the bzip2 package.


%package staticdev
Summary: staticdev components for the bzip2 package.
Group: Default
Requires: bzip2-dev = %{version}-%{release}

%description staticdev
staticdev components for the bzip2 package.


%package staticdev32
Summary: staticdev32 components for the bzip2 package.
Group: Default
Requires: bzip2-dev = %{version}-%{release}

%description staticdev32
staticdev32 components for the bzip2 package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) FC57E3CCACD99A78' gpg.status
%setup -q -n bzip2-1.0.8
cd %{_builddir}/bzip2-1.0.8
%patch -P 1 -p1
%patch -P 2 -p1
pushd ..
cp -a bzip2-1.0.8 build32
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1740616881
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CFLAGS_GENERATE="$CLEAR_INTERMEDIATE_CFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic "
export FCFLAGS_GENERATE="$CLEAR_INTERMEDIATE_FCFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic "
export FFLAGS_GENERATE="$CLEAR_INTERMEDIATE_FFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic "
export CXXFLAGS_GENERATE="$CLEAR_INTERMEDIATE_CXXFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic "
export LDFLAGS_GENERATE="$CLEAR_INTERMEDIATE_LDFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic "
export CFLAGS_USE="$CLEAR_INTERMEDIATE_CFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "
export FCFLAGS_USE="$CLEAR_INTERMEDIATE_FCFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "
export FFLAGS_USE="$CLEAR_INTERMEDIATE_FFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "
export CXXFLAGS_USE="$CLEAR_INTERMEDIATE_CXXFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "
export LDFLAGS_USE="$CLEAR_INTERMEDIATE_LDFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
CFLAGS="${CFLAGS_GENERATE}" CXXFLAGS="${CXXFLAGS_GENERATE}" FFLAGS="${FFLAGS_GENERATE}" FCFLAGS="${FCFLAGS_GENERATE}" LDFLAGS="${LDFLAGS_GENERATE}" %reconfigure
make  %{?_smp_mflags}

cp /usr/bin/x86_64-generic-linux-gcc .
LD_LIBRARY_PATH=. ./bzip2 -9 manual.ps
LD_LIBRARY_PATH=. ./bzip2 -9 configure
LD_LIBRARY_PATH=. ./bzip2 x86_64-generic-linux-gcc
LD_LIBRARY_PATH=. ./bzip2 -d manual.ps.bz2
LD_LIBRARY_PATH=. ./bzip2 -d configure.bz2
LD_LIBRARY_PATH=. ./bzip2 -d x86_64-generic-linux-gcc.bz2
make clean
export GOAMD64=v2
CFLAGS="${CFLAGS_USE}" CXXFLAGS="${CXXFLAGS_USE}" FFLAGS="${FFLAGS_USE}" FCFLAGS="${FCFLAGS_USE}" LDFLAGS="${LDFLAGS_USE}" %reconfigure
make  %{?_smp_mflags}
pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig:/usr/share/pkgconfig"
ASFLAGS="${CLEAR_INTERMEDIATE_ASFLAGS}${CLEAR_INTERMEDIATE_ASFLAGS:+ }--32"
CFLAGS="${CLEAR_INTERMEDIATE_CFLAGS}${CLEAR_INTERMEDIATE_CFLAGS:+ }-m32 -mstackrealign"
CXXFLAGS="${CLEAR_INTERMEDIATE_CXXFLAGS}${CLEAR_INTERMEDIATE_CXXFLAGS:+ }-m32 -mstackrealign"
LDFLAGS="${CLEAR_INTERMEDIATE_LDFLAGS}${CLEAR_INTERMEDIATE_LDFLAGS:+ }-m32 -mstackrealign"
%reconfigure    --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CFLAGS_GENERATE="$CLEAR_INTERMEDIATE_CFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic "
export FCFLAGS_GENERATE="$CLEAR_INTERMEDIATE_FCFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic "
export FFLAGS_GENERATE="$CLEAR_INTERMEDIATE_FFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic "
export CXXFLAGS_GENERATE="$CLEAR_INTERMEDIATE_CXXFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic "
export LDFLAGS_GENERATE="$CLEAR_INTERMEDIATE_LDFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic "
export CFLAGS_USE="$CLEAR_INTERMEDIATE_CFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "
export FCFLAGS_USE="$CLEAR_INTERMEDIATE_FCFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "
export FFLAGS_USE="$CLEAR_INTERMEDIATE_FFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "
export CXXFLAGS_USE="$CLEAR_INTERMEDIATE_CXXFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "
export LDFLAGS_USE="$CLEAR_INTERMEDIATE_LDFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1740616881
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/bzip2
cp %{_builddir}/bzip2-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/bzip2/ddf157bc55ed6dec9541e4af796294d666cd0926 || :
export GOAMD64=v2
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
if [ -d %{buildroot}/usr/share/pkgconfig ]
then
pushd %{buildroot}/usr/share/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
GOAMD64=v2
%make_install
## install_append content
# fix SONAME so all dependent libraries are happy with this
for curr in 32 64; do
patchelf --set-soname libbz2.so.1.0 %{buildroot}/usr/lib${curr}/libbz2.so.1.0.0
ln -sf libbz2.so.1.0.0 %{buildroot}/usr/lib${curr}/libbz2.so.1.0
# create compat libs as well
rm -f %{buildroot}/usr/lib${curr}/libbz2.so.0
cp %{buildroot}/usr/lib${curr}/libbz2.so.1.0.0 %{buildroot}/usr/lib${curr}/libbz2.so.0.0.0
patchelf --set-soname libbz2.so.0 %{buildroot}/usr/lib${curr}/libbz2.so.0.0.0
ln -sf libbz2.so.0.0.0 %{buildroot}/usr/lib${curr}/libbz2.so.0
rm -f %{buildroot}/usr/lib${curr}/libbz2.so.1
cp %{buildroot}/usr/lib${curr}/libbz2.so.1.0.0 %{buildroot}/usr/lib${curr}/libbz2.so.1
patchelf --set-soname libbz2.so.1 %{buildroot}/usr/lib${curr}/libbz2.so.1
# for steam
ln -sf libbz2.so.1.0.0 %{buildroot}/usr/lib${curr}/libbz2.so.%{version}
done
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/bunzip2
/usr/bin/bzcat
/usr/bin/bzcmp
/usr/bin/bzdiff
/usr/bin/bzegrep
/usr/bin/bzfgrep
/usr/bin/bzgrep
/usr/bin/bzip2
/usr/bin/bzip2recover
/usr/bin/bzless
/usr/bin/bzmore

%files dev
%defattr(-,root,root,-)
/usr/include/bzlib.h
/usr/lib64/libbz2.so
/usr/lib64/pkgconfig/bzip2.pc

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libbz2.so
/usr/lib32/pkgconfig/32bzip2.pc
/usr/lib32/pkgconfig/bzip2.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libbz2.so.0
/usr/lib64/libbz2.so.0.0.0
/usr/lib64/libbz2.so.1
/usr/lib64/libbz2.so.1.0
/usr/lib64/libbz2.so.1.0.0
/usr/lib64/libbz2.so.1.0.8

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libbz2.so.0
/usr/lib32/libbz2.so.0.0.0
/usr/lib32/libbz2.so.1
/usr/lib32/libbz2.so.1.0
/usr/lib32/libbz2.so.1.0.0
/usr/lib32/libbz2.so.1.0.8

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/bzip2/ddf157bc55ed6dec9541e4af796294d666cd0926

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/bzcmp.1
/usr/share/man/man1/bzdiff.1
/usr/share/man/man1/bzegrep.1
/usr/share/man/man1/bzfgrep.1
/usr/share/man/man1/bzgrep.1
/usr/share/man/man1/bzip2.1
/usr/share/man/man1/bzless.1
/usr/share/man/man1/bzmore.1

%files staticdev
%defattr(-,root,root,-)
/usr/lib64/libbz2.a

%files staticdev32
%defattr(-,root,root,-)
/usr/lib32/libbz2.a
